apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: opencollab
  destination:
    namespace: opencollab
    server: https://kubernetes.default.svc
  source:
    path: components/argocd/production
    repoURL: https://github.com/opencollab/infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true