apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: downloads
  namespace: opencollab
spec:
  project: opencollab
  destination:
    namespace: opencollab
    server: https://kubernetes.default.svc
  source:
    path: components/downloads/production
    repoURL: git@github.com:opencollaboration/infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
