apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opencollab-access
  namespace: geysermc
subjects:
  - kind: ServiceAccount
    name: geysermc
    namespace: opencollab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
